name: Tidy Go Mod

on:
  push:
    branches:
      - main

jobs:
  tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run go mod tidy
        run: |
          go mod tidy
          if ! git diff --quiet; then
            echo "==> Tidy changes detected, preparing PR"
            git config user.name "Mirror Bot"
            git config user.email "mirror-bot@github"

            # Create a new branch for the tidy changes
            BRANCH_NAME="tidy/update-$(date +%s)"
            git checkout -b $BRANCH_NAME

            git add go.mod go.sum
            git commit -m "chore: tidy go.mod and go.sum"
            git push origin $BRANCH_NAME

            # Create a PR and auto-merge it
            gh pr create --fill --base main --head $BRANCH_NAME
            gh pr merge --auto --delete-branch
          else
            echo "==> No tidy changes detected"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
